-- BLACK CELL Gestão: estrutura PostgreSQL/Supabase para substituir o adaptador local.
create table customers (id uuid primary key default gen_random_uuid(), name text not null, whatsapp text not null, note text, created_at timestamptz default now());
create table products (id uuid primary key default gen_random_uuid(), model text not null, storage text not null, color text not null, quantity integer not null check (quantity >= 0), cost numeric(12,2) not null check (cost >= 0), price numeric(12,2) not null check (price >= 0), created_at timestamptz default now());
create table sales (id uuid primary key default gen_random_uuid(), customer_id uuid references customers not null, sold_at date not null default current_date, payment_method text not null, total numeric(12,2) not null check (total > 0), installments_count integer not null check (installments_count > 0), created_at timestamptz default now());
create table sale_items (id uuid primary key default gen_random_uuid(), sale_id uuid references sales on delete cascade not null, product_id uuid references products not null, quantity integer not null check (quantity > 0), unit_price numeric(12,2) not null check (unit_price > 0));
create table installments (id uuid primary key default gen_random_uuid(), sale_id uuid references sales on delete cascade not null, number integer not null, amount numeric(12,2) not null check (amount > 0), due_date date not null, paid_at timestamptz, payment_method text, unique(sale_id, number));
create table stock_movements (id uuid primary key default gen_random_uuid(), product_id uuid references products not null, type text not null check (type in ('entry','exit','sale')), quantity integer not null, note text, created_at timestamptz default now());
create table whatsapp_messages (id uuid primary key default gen_random_uuid(), installment_id uuid references installments not null, kind text not null check (kind in ('due_today','overdue')), sent_at timestamptz default now(), provider_message_id text);
create table settings (key text primary key, value jsonb not null, updated_at timestamptz default now());
